---
title: "What checks are performed?"
author: "Martin Barner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{What checks are performed?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

This packages checks for inconsistencies between xlsform questionnaires (kobo tools), datasets and analysis plans.
There is a function to check each input, and to check each combination:

Runs all checks (depending on which input is provided):

- check_input()



## Which Issues may be raised? - individual inputs

### Data

- _data is not a data.frame_ (critical)
- _duplicate data column header_ (critical)

### Questionnaire Questions

- _questions are not a data frame_ (critical)
- _questions do not contain column 'type'_ (critical)
- _questions do not contain column 'name'_ (critical)
- _illegal question type_ (critical)
- _variable [[variable name]] used in 'relevant' column not found in question 'name'_ (critical)
- _failed to evaluate 'relevant' condition_ (critical)
- _questions do not contain a column with the word 'label'_ (minor)

### Questionnaire Choices

- _choices is not a data frame_ (critical)


### Sampling frame
- _could not check samplingframe_ (critical)

- _samplingframe has no categorical column (stratum names) - skipping further checks on stratum column_ (critical)
- _samplingframe has more than one categorical column (stratum names) - skipping further checks on stratum column_ (critical)

- _samplingframe has no purely numerical (population) column - skipping any further checks on population column_ (critical)
- _samplingframe has more than one numerical (population) column_ (critical)
- _no stratum can have 0 or negative population_ (critical)
- _duplicate stratum name in samplingframe_ (critical)
- _samplingframe must not contain NAs_ (critical)

- _samplingframe should only have two columns_ (minor)


### Analysis plan
- _could not check analysisplan - not a data.frame_ (critical)
- _could not check analysisplan - 0 rows_ (critical)
- _could not check analysisplan standard variables (not a data frame)_ (critical)
- _could not find standardised column names in analysis plan_ (critical)


## Which Issues may be raised? - inconsistencies between different inputs

### Data vs. Questionnaire

- _could not check data against questionnaire (i.e. koboquest::load_questionnaire() throws an error)_ (critical)
- _choices is not a data frame_ (critical)
- _data type does not match type defined in questionnaire_ (critical)
- _data column not found in questionnaire_ (minor)
- _select_one or select_multiple values in data that are not listed in the questionnaire_ (minor)


### Data vs. Analysis Plan
- _could not check match between data and analysis plan - data is not a data.frame_ (critical)
- _could not check match between data and analysis plan - analysisplan is not a data.frame_ (critical)
- _analysisplan variable not in data_ (critical)

<!-- ## checks that are not (yet) implemented but should be: -->
<!-- check_input_match_data_samplingframe<-function(samplingframe,data){} -->
<!-- check_input_match_questionnaire_samplingframe<-function(samplingframe,data){} -->
<!-- check_input_match_questionnaire_analysisplan<-function(samplinframe,data){} -->
<!-- check_input_match_data_analysisplan<-function(samplinframe,data){} -->
